source 'https://rubygems.org'

gem 'rails', '3.2.11'

gem 'sqlite3'

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'compass-rails'
  gem 'zurb-foundation'

  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'
gem 'haml'
gem "mongoid", "~> 3.0.22"
gem "handlebars", "~> 0.3.2"


